### ISSUE TITLE
How to import contacts from existing databases?

### ISSUE THREAD

**Issue by poetaman** [lucc/khard#287]
Can you please add steps needed to import contacts from existing databases? Am looking forward to import contacts from macOS in-built Contacts app. I can select all contacts, and export them as one "vcards" file. Not sure how to import it using Khard. I mean there should be an option to say ``khard --import <filename or directory_name>``

**Comment by lucc** [comment]
As described [in the docs](https://khard.readthedocs.io/en/latest/scripting.html#integration) you will need to have the contacts from your existing database in individual vcard files.  One big file with many vcards is not supported.

If our underlying vobject library supports single files with many vcard objects inside an import function should be possible to implement. The import command could accept input in vcard format and normalize them (add a uid e.g.) as well as vaddressbook I would be open for pull requests.

There has been some discussion about this before: #252

**Comment by rogarb** [comment]
As I was setting up `khard` for managing my email client contacts, I also faced the issue of splitting my vcf files, but before I could find this issue, I had written a python script to do it ([vcf-splitter](https://framagit.org/rogarb/vcf-splitter) for the record).

My point is: shouldn't the docs be updated to mention some scripts for splitting existing vcf files? I can create a PR with a modified version of i.e. `doc/source/scripting.rst` referencing the tools mentioned in this issue.

**Comment by lucc** [comment]
@rogarb PR welcome!

**Comment by lucc** [comment]
@poetaman I will close this as #317 is merged. 

If someone still needs a new subcommand in khard they can use `vobject.readComponents` and send a PR.

**Comment by Sylvain303** [comment]
Is the doc change [9a49b69](https://github.com/rogarb/khard/commit/9a49b695265e6e1b772666b5b60bf9a052cac578) published on https://khard.readthedocs.io/en/latest/scripting.html ?

**Comment by lucc** [comment]
@Sylvain303 yes, please use the search function of your browser. It is here https://khard.readthedocs.io/en/latest/scripting.html#integration
