### ISSUE TITLE
Travis.org has been shut down

### ISSUE THREAD

**Issue by lucc** [lucc/khard#292]
travis-ci.org was finally shut down ([blog entry](https://blog.travis-ci.com/2021-05-07-orgshutdown)) and if we want to continue using travis we have to use travis-ci.com

Our old builds are still on org but the newest one is already failing:
https://travis-ci.org/github/scheibler/khard/builds
And new PRs won't get build.

# Solutions
- we move to travis-ci.com
- we use github actions instead

@scheibler I need your help with either solution as I do not have enough access rights on this repo to d it alone. We might prefer travis as we can use our current config with that. We might not prefer github actions because we have to set up a new config, but we might prefer GA because there is less fiddling around with access right and github-apps and accounts.

I have switched to travis-ci.com for lucc/nvimpager and have used github actions for my master thesis, so I am fine with either one, I just want to have CI :)

**Comment by d7415** [comment]
Moving to .com would be simpler because the configuration should be identical. Their OSS credits system is a pain though. That said, one batch of credits would probably last this project a while as I think it's usually 10,000.

Like you say, up to @scheibler though.

**Comment by lucc** [comment]
Fixed with #307
