### ISSUE TITLE
Reduce empty address lines in "details" output + patch

### ISSUE THREAD

**Issue by sciurius** [lucc/khard#295]
To reduce empty address lines in "details" output something similar to the attached patch could be considered.

For example, output before the patch:
````
Address
    HOME: 
        Main street 20

        1234 AB Blaricum
        , Netherlands
````
After the patch:
````
Address
    HOME: 
        Main street 20
        1234 AB Blaricum
        Netherlands
````
[reduce_empty_address_lines.patch.txt](https://github.com/scheibler/khard/files/6865182/reduce_empty_address_lines.patch.txt)

**Comment by lucc** [comment]
This was already merged in #297.
