### ISSUE TITLE
Single ics file

### ISSUE THREAD

**Issue by avidseeker** [lucc/khard#318]
Whenever a new event is created or imported, khal creates a whole new ics file just for that event.

Typical calendar services combine all calendar events into one ics file. E.g: schedule.ics, work.ics, academic.ics, and so on...

It would be more cleaner if khal can combine events into a single ics file and keeps it updated.

**Comment by lucc** [comment]
This repo is khard the address book, you want [khal](https://github.com/pimutils/khal) the calendar.
