### ISSUE TITLE
Having the string 'github-username' in private objects causes only it to be read.

### ISSUE THREAD

**Issue by SamuelSwartzberg** [lucc/khard#322]
Now this is an odd bug. Removing the hyphen, or changing it to `github-usrname` allows the following private objects in private_objects to be read, but the exact string 'github-username' causes problems.

Repro:

`private_objects = github-username, translation-rate`

Is: 

Only github-username is recognized as a private object, translation-rate is omitted when editing an existing contact (other cases not tested)

Should be:

Both github-username and translation-rate are recognized as private objects in the above case.

**Comment by d7415** [comment]
> when editing an existing contact 

Did the existing contact have `github-username` specified but not `translation-rate`? Only fields that already have values are shown in khard for me. Showing empty fields would probably be a useful enhancement though.

**Comment by lucc** [comment]
I can not reproduce this. At least not with `khard show` and `khard edit`.

Can you please post a minimal working example (config+vcards) to reproduce this. It might be good to remove any personal info from the vcards. Please also state which subcommand  of khard you are using.

I assume you are using the latest khard from the develop branch.

**Comment by lucc** [comment]
Closed due to inactivity.
