### ISSUE TITLE
Import VCF with single contact

### ISSUE THREAD

**Issue by timmli** [lucc/khard#330]
What is the recommended way to import a VCF with a single contact into Khard's database?

I have tried `khard new --input-file contact.vcf` (v0.17.0) but that was unsuccessful. 

There is an issue that sounds similar: https://github.com/lucc/khard/issues/287
My problem, however, is not having single files with many contacts.

**Comment by lucc** [comment]
There is no import command for vcf files. You can simply copy/move the file into khard's address book folder because internally khard uses vcards to store contacts.

**Comment by timmli** [comment]
Moving the VCF  to the address book (vdir) does not work in my case, because the VCF does not yet have a UID. 
Any suggestions how to handle VCF without UID?
